# Do NOT update manually; changes here will be overwritten by Copier
_commit: 44dde56
_src_path: https://github.com/openg2p/openg2p-fastapi-template
github_ci_docker_build: true
github_ci_openapi_publish: true
github_ci_precommit: true
github_ci_pypi_publish: true
github_ci_tests: true
github_ci_tests_codecov: true
module_name: openg2p_g2pconnect_common_lib
org_name: OpenG2P
org_slug: OpenG2P
package_name: openg2p-g2pconnect-common-lib
repo_name: OpenG2P G2PConnect Common Libraries
repo_slug: openg2p-g2pconnect-common

