name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      buildNumber:
        description: 'Build Number'
        required: false
        type: string

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution Common
      run: python -m build ./openg2p-g2pconnect-common-lib
    - name: Build distribution Mapper
      run: python -m build ./openg2p-g2pconnect-mapper-lib
    - name: Add build number to package
      if: inputs.buildNumber != ''
      run: |
        cd openg2p-g2pconnect-common-lib/dist
        for file in *.whl; do
          echo $file
          IFS=- read distribution version rest <<< "$file"
          mv $file "${distribution}-${version}-${{ inputs.buildNumber }}-${rest}"
        done
        for file in *.tar.gz; do
          echo $file
          IFS=- read distribution version <<< "$file"
          mv $file "${distribution}-${version//.tar.gz/-${{ inputs.buildNumber }}}.tar.gz"
        done
        cd ../../openg2p-g2pconnect-mapper-lib/dist
        for file in *.whl; do
          echo $file
          IFS=- read distribution version rest <<< "$file"
          mv $file "${distribution}-${version}-${{ inputs.buildNumber }}-${rest}"
        done
        for file in *.tar.gz; do
          echo $file
          IFS=- read distribution version <<< "$file"
          mv $file "${distribution}-${version//.tar.gz/-${{ inputs.buildNumber }}}.tar.gz"
        done
    - name: Publish Common
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: openg2p-g2pconnect-common-lib/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish Mapper
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: openg2p-g2pconnect-mapper-lib/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
